### PR TITLE
Feature/level design intro

### PR DESCRIPTION
**Pull request by ambid17**

### CODE REVIEW

**Comment by 0xLeif** [comment]
```
isPortalLevel: 0
isSurfLevel: 0
```

Can both these be true?
```
isPortalLevel: 1
isSurfLevel: 1
```


Where are they used?

**Comment by ambid17** [comment]
> ```
> isPortalLevel: 0
> isSurfLevel: 0
> ```
> 
> Can both these be true?
> 
> ```
> isPortalLevel: 1
> isSurfLevel: 1
> ```
> 
> Where are they used?

The `isPortalLevel` is used to determine whether the player can spawn portals in the PortalPlacement.cs script. I need to remove `isSurfLevel` thanks for the reminder!

**Review by Vextin — APPROVED** [review]
Could use a comment describing 'Overbounce' but functionally looks good!

**Review by 0xLeif — APPROVED** [review]

**Comment by 0xLeif** [comment]
> > ```
> > isPortalLevel: 0
> > isSurfLevel: 0
> > ```
> > 
> > 
> > Can both these be true?
> > ```
> > isPortalLevel: 1
> > isSurfLevel: 1
> > ```
> > 
> > 
> > Where are they used?
> 
> 
> The `isPortalLevel` is used to determine whether the player can spawn portals in the PortalPlacement.cs script. I need to remove `isSurfLevel` thanks for the reminder!

Cool! Thanks :D

**Pull request merged**
