### PR TITLE
Patch/collision issues

### PR DESCRIPTION
**Pull request by ambid17**
Made a new ground detection system to prevent various collision issues

### CODE REVIEW

**Comment by ambid17** [comment]
Closes #92 #98 #104. turns out they are all the same issue

**Comment by ambid17** [comment]
Closes #97

**Comment by ambid17** [comment]
Closes #105

**Review by FuhrmannMaciej — DISMISSED** [review]
Looks good :)

**Comment by ambid17** [comment]
Closes #107

**Pull request merged**
